# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Laplace density function
#' @description Standard Laplace density function
#' @param x a real number
#' @return the density at \code{x}
#' @examples
#' @export
dlaplace <- function(x) {
    .Call('_StatComp20026_dlaplace', PACKAGE = 'StatComp20026', x)
}

#' @title Random walk Metropolis sampler
#' @description generate random samples from standard laplace distribution using random walk Metropolis sampler
#' @param sigma the standard deviation for Gaussian increment
#' @param x0 initial point of random walk
#' @param N the numer of wanted samples
#' @return a list containing the samples and the number of rejected points
#' @useDynLib StatComp20026
#' @examples
#' @export
rwM <- function(sigma, x0, N) {
    .Call('_StatComp20026_rwM', PACKAGE = 'StatComp20026', sigma, x0, N)
}

